### ISSUE TITLE
batch mode → large image folder

### ISSUE THREAD

**Issue by roboto-cloud** [ajstarks/gift#1]
Hi @ajstarks, do you know how use it in batch mode?

**something like:**

`gift -contrast 80 ./in-folder > ./out-folder
`
Thanks in advance,

**Comment by ajstarks** [comment]
You can loop over the files and process each individually

On a Unix-like system (you should take care to manage filenames with spaces)

```
#!/bin/sh
cd in-folder
for i in *
do
    gift -contrast 80 < "$i" > out-folder/"$i"
done
```
